# Generated by Django 5.2.1 on 2025-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
    ]
