# Generated by Django 5.2.1 on 2025-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_prize_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
